// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// disc_dataset_bb_cpp
arma::Mat<int> disc_dataset_bb_cpp(const arma::mat& expr_data, const int n_cores);
RcppExport SEXP _fastGeneMI_disc_dataset_bb_cpp(SEXP expr_dataSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type expr_data(expr_dataSEXP);
    Rcpp::traits::input_parameter< const int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(disc_dataset_bb_cpp(expr_data, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// get_bb_bin_edges_cpp
arma::vec get_bb_bin_edges_cpp(const arma::vec& expr_prof);
RcppExport SEXP _fastGeneMI_get_bb_bin_edges_cpp(SEXP expr_profSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type expr_prof(expr_profSEXP);
    rcpp_result_gen = Rcpp::wrap(get_bb_bin_edges_cpp(expr_prof));
    return rcpp_result_gen;
END_RCPP
}
// mim_bspline_cpp
arma::mat mim_bspline_cpp(const arma::mat& expr_data, const int k, const int n_bins, const int n_cores);
RcppExport SEXP _fastGeneMI_mim_bspline_cpp(SEXP expr_dataSEXP, SEXP kSEXP, SEXP n_binsSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type expr_data(expr_dataSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const int >::type n_bins(n_binsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(mim_bspline_cpp(expr_data, k, n_bins, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// mim_ML_cpp
arma::mat mim_ML_cpp(const arma::mat& disc_expr_data, int n_cores);
RcppExport SEXP _fastGeneMI_mim_ML_cpp(SEXP disc_expr_dataSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type disc_expr_data(disc_expr_dataSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(mim_ML_cpp(disc_expr_data, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// mim_MM_cpp
arma::mat mim_MM_cpp(const arma::mat& disc_expr_data, int n_cores);
RcppExport SEXP _fastGeneMI_mim_MM_cpp(SEXP disc_expr_dataSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type disc_expr_data(disc_expr_dataSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(mim_MM_cpp(disc_expr_data, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// mim_CS_cpp
arma::mat mim_CS_cpp(const arma::mat& disc_expr_data, int n_cores);
RcppExport SEXP _fastGeneMI_mim_CS_cpp(SEXP disc_expr_dataSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type disc_expr_data(disc_expr_dataSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(mim_CS_cpp(disc_expr_data, n_cores));
    return rcpp_result_gen;
END_RCPP
}
// mim_shrink_cpp
arma::mat mim_shrink_cpp(const arma::mat& disc_expr_data, int n_cores);
RcppExport SEXP _fastGeneMI_mim_shrink_cpp(SEXP disc_expr_dataSEXP, SEXP n_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type disc_expr_data(disc_expr_dataSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(mim_shrink_cpp(disc_expr_data, n_cores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastGeneMI_disc_dataset_bb_cpp", (DL_FUNC) &_fastGeneMI_disc_dataset_bb_cpp, 2},
    {"_fastGeneMI_get_bb_bin_edges_cpp", (DL_FUNC) &_fastGeneMI_get_bb_bin_edges_cpp, 1},
    {"_fastGeneMI_mim_bspline_cpp", (DL_FUNC) &_fastGeneMI_mim_bspline_cpp, 4},
    {"_fastGeneMI_mim_ML_cpp", (DL_FUNC) &_fastGeneMI_mim_ML_cpp, 2},
    {"_fastGeneMI_mim_MM_cpp", (DL_FUNC) &_fastGeneMI_mim_MM_cpp, 2},
    {"_fastGeneMI_mim_CS_cpp", (DL_FUNC) &_fastGeneMI_mim_CS_cpp, 2},
    {"_fastGeneMI_mim_shrink_cpp", (DL_FUNC) &_fastGeneMI_mim_shrink_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastGeneMI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
